echo sadasd > a.txt
echo sadasd > b.txt
echo sadafds > c.txt
echo sadasdads > d.txt
echo sadasd > e.txt
echo sadasdasdasdgfdsg > r.txt
echo sadasd > a.rtf
echo sadasd > b.rtf
echo sadafds > c.rtf
echo sadasdads > d.rtf
echo sadasd > e.rtf
echo sadasdasdasdgfdsg > r.rtf
echo sadasd > a.doc
echo sadasd > b.doc
echo sadafds > c.doc
echo sadasdads > d.doc
echo sadasd > e.doc
echo sadasdasdasdgfdsg > r.doc
echo sadasd > a.docx
echo sadasd > b.docx
echo sadafds > c.docx
echo sadasdads > d.docx
echo sadasd > e.docx
echo sadasdasdasdgfdsg > r.docx
echo sadasd > a.pdf
echo sadasd > b.pdf
echo sadafds > c.pdf
echo sadasdads > d.pdf
echo sadasd > e.pdf
echo sadasdasdasdgfdsg > r.pdf
echo sadasd > a.xlsx
echo sadasd > b.xlsx
echo sadafds > c.xlsx
echo sadasdads > d.xlsx
echo sadasd > e.xlsx
echo sadasdasdasdgfdsg > r.xlsx
echo sadasd > a.pptx
echo sadasd > b.pptx
echo sadafds > c.pptx
echo sadasdads > d.pptx
echo sadasd > e.pptx
echo sadasdasdasdgfdsg > r.pptx
echo sadasd > a.ppsx
echo sadasd > b.ppsx
echo sadafds > c.ppsx
echo sadasdads > d.ppsx
echo sadasd > e.ppsx
echo sadasdasdasdgfdsg > r.ppsx